name: Fetch and Update Data

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:      # Allow manual trigger

jobs:
  fetch_and_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Required for PAT authentication

      - name: Fetch new data from remote
        run: |
          curl -sSL https://yasserbdj96.pythonanywhere.com/data.json -o new_data.json

      - name: Compare new data with existing
        id: compare
        run: |
          target_path="Front-End/data.json"
          if [ ! -f "$target_path" ]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          elif ! cmp -s new_data.json "$target_path"; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit and push updated data
        if: steps.compare.outputs.changed == 'true'
        run: |
          cp new_data.json Front-End/data.json
          git config user.name "Auto Updater"
          git config user.email "auto-updater@example.com"
          git add Front-End/data.json
          git commit -m "Update data.json from remote source"
          git push https://yasserbdj96:${{ secrets.GH_PAT }}@github.com/yasserbdj96/Portfolio.git main
